import { Service, Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'maintenance',
    nameEn: 'Home Maintenance',
    nameAr: 'صيانة المنزل',
    descriptionEn: 'High-quality on-demand maintenance services for your home with transparent pricing.',
    descriptionAr: 'خدمات صيانة منزلية عالية الجودة عند الطلب مع تسعير شفاف ومحدد.',
    icon: 'Hammer'
  },
  {
    id: 'consultation',
    nameEn: 'Professional Consultations',
    nameAr: 'الاستشارات المهنية',
    descriptionEn: 'Expert engineering, designing, and contracting consultations from industry professionals.',
    descriptionAr: 'استشارات هندسية وتصميم ومقاولات متخصصة من محترفين مرخصين.',
    icon: 'Briefcase'
  }
];

export const INITIAL_SERVICES: Service[] = [
  // Maintenance Services
  {
    id: 'plumbing',
    categoryId: 'maintenance',
    nameEn: 'Plumbing',
    nameAr: 'السباكة',
    descriptionEn: 'Fix leaks, repair faucets, replace pipes, and handle all water system issues.',
    descriptionAr: 'إصلاح التسريبات، الصنبور، تمديد الأنابيب، معالجة كافة مشاكل المياه والصرف.',
    bookingFee: 45,
    icon: 'Wrench'
  },
  {
    id: 'electricity',
    categoryId: 'maintenance',
    nameEn: 'Electricity',
    nameAr: 'الكهرباء',
    descriptionEn: 'Wiring, outlet repairs, light fixture installations, and electrical troubleshooting.',
    descriptionAr: 'تمديد الأسلاك، إصلاح المقابس، تركيب تجهيزات الإضاءة، واستكشاف الأعطال الكهربائية وإصلاحها.',
    bookingFee: 50,
    icon: 'Zap'
  },
  {
    id: 'paint',
    categoryId: 'maintenance',
    nameEn: 'Paint',
    nameAr: 'الدهان والطلاء',
    descriptionEn: 'Wall painting, touch-ups, accent walls, and complete interior/exterior painting.',
    descriptionAr: 'طلاء الجدران، معالجة الشقوق والخدوش، طلاء الغرف بالكامل داخلياً وخارجياً.',
    bookingFee: 75,
    icon: 'Paintbrush'
  },
  {
    id: 'aluminum',
    categoryId: 'maintenance',
    nameEn: 'Aluminum Works',
    nameAr: 'أعمال الألمنيوم',
    descriptionEn: 'Installing, repairing, and maintenance of aluminum window frames and doors.',
    descriptionAr: 'تركيب، إصلاح وصيانة إطارات النوافذ والأبواب المصنوعة من الألمنيوم.',
    bookingFee: 40,
    icon: 'Columns3'
  },
  {
    id: 'tiling',
    categoryId: 'maintenance',
    nameEn: 'Tiling',
    nameAr: 'البلاط والسيراميك',
    descriptionEn: 'Tile installation, regrouting, and repairs for bathroom, kitchen, and living room floors.',
    descriptionAr: 'تركيب البلاط والسيراميك، إعادة الترويبة، وإصلاح الأرضيات التالفة بالمطابخ والحمامات.',
    bookingFee: 90,
    icon: 'Grid3X3'
  },
  {
    id: 'woodwork',
    categoryId: 'maintenance',
    nameEn: 'Woodwork & Carpentry',
    nameAr: 'النجارة والأخشاب',
    descriptionEn: 'Furniture repairs, door hanging, cabinet installation, and lock replacement.',
    descriptionAr: 'إصلاح الأثاث الخشبي، تركيب الأبواب والخزائن، وتغيير الأقفال والمفصلات.',
    bookingFee: 60,
    icon: 'Notebook'
  },
  {
    id: 'steelwork',
    categoryId: 'maintenance',
    nameEn: 'Steelwork & Welding',
    nameAr: 'أعمال الحديد والحدادة',
    descriptionEn: 'Welding services, gate repairs, security grill installations, and steel modifications.',
    descriptionAr: 'خدمات اللحام، إصلاح البوابات وحمايات النوافذ الحديدية والتعديلات الهيكلية.',
    bookingFee: 80,
    icon: 'Boxes'
  },
  {
    id: 'ac',
    categoryId: 'maintenance',
    nameEn: 'Air Conditioning',
    nameAr: 'التكييف والتبريد',
    descriptionEn: 'Filter cleaning, refrigerant recharging, and full diagnosis of AC units.',
    descriptionAr: 'تنظيف الفلاتر، إعادة تعبئة الفريون، والفحص الكامل لوحدات التكييف المختلفة.',
    bookingFee: 55,
    icon: 'Snowflake'
  },
  {
    id: 'mechanical',
    categoryId: 'maintenance',
    nameEn: 'Mechanical Works',
    nameAr: 'الأعمال الميكانيكية',
    descriptionEn: 'Pumps, water heaters, and mechanical appliance inspection and repair.',
    descriptionAr: 'صيانة وإصلاح مضخات المياه، السخانات، والأجهزة الميكانيكية المنزلية.',
    bookingFee: 65,
    icon: 'Settings'
  },
  {
    id: 'gardening',
    categoryId: 'maintenance',
    nameEn: 'Gardening & Landscaping',
    nameAr: 'الحدائق والزراعة',
    descriptionEn: 'Lawn mowing, tree trimming, irrigation system checks, and plant curation.',
    descriptionAr: 'قص العشب، تشذيب الأشجار، فحص شبكات الري، وتنسيق المزروعات والنباتات.',
    bookingFee: 40,
    icon: 'Sprout'
  },
  {
    id: 'insulation',
    categoryId: 'maintenance',
    nameEn: 'Insulation',
    nameAr: 'العزل الحراري والمائي',
    descriptionEn: 'Roof and wall sealing to prevent leaks and maximize energy efficiency.',
    descriptionAr: 'عزل الأسطح والجدران لمنع تسرب المياه وتقليل استهلاك الطاقة والكهرباء.',
    bookingFee: 100,
    icon: 'Shield'
  },
  {
    id: 'inspection',
    categoryId: 'maintenance',
    nameEn: '🏠 Full Home Inspection',
    nameAr: '🏠 فحص شامل للمنزل',
    descriptionEn: 'Comprehensive end-to-end check of your home structural, plumbing, and electrical status.',
    descriptionAr: 'فحص مالي وإنشائي وفني وهندسي شامل لكافة تمديدات المياه، الكهرباء، وهيكل المنزل.',
    bookingFee: 150,
    icon: 'Eye'
  },

  // Consultations
  {
    id: 'mech_eng',
    categoryId: 'consultation',
    nameEn: 'Mechanical Engineer',
    nameAr: 'مهندس ميكانيك',
    descriptionEn: 'Professional HVAC, ventilation, heating, elevator, and pump network consultations.',
    descriptionAr: 'استشارات احترافية في شبكات التهوية، التكييف المركزي، المصاعد ومضخات المياه.',
    icon: 'Cpu'
  },
  {
    id: 'contractor',
    categoryId: 'consultation',
    nameEn: 'Contractor',
    nameAr: 'مقاول بناء',
    descriptionEn: 'Advice on structural extensions, renovation budgets, and concrete structures.',
    descriptionAr: 'استشارات عن التوسعات الإنشائية، ميزانية الترميم، والهياكل الخرسانية والمباني.',
    icon: 'HardHat'
  },
  {
    id: 'architect',
    categoryId: 'consultation',
    nameEn: 'Architect',
    nameAr: 'مهندس معماري',
    descriptionEn: 'Layout planning, spatial planning, and building exterior designs and permits.',
    descriptionAr: 'تخطيط المساحات، المخططات الهيكلية، وتصميم الواشفات والترخيص.',
    icon: 'Map'
  },
  {
    id: 'interior',
    categoryId: 'consultation',
    nameEn: 'Interior Designer',
    nameAr: 'مصمم داخلي',
    descriptionEn: 'Material selection, lighting design, colors, layouts, and high-end furniture sourcing.',
    descriptionAr: 'استشارات في اختيار الخامات، تصاميم الإضاءة، الألوان، الأثاث والنمط الجمالي.',
    icon: 'Palette'
  }
];

export const TRANSLATIONS = {
  en: {
    appName: 'HOMEPLEX',
    appSubtitle: 'PRO MAINTENANCE & CONSULTING',
    navHome: 'Home',
    navBookings: 'My Bookings',
    navAdmin: 'Admin Panel',
    navLogin: 'Log In',
    navSignup: 'Register',
    navLogout: 'Sign Out',
    welcomeBack: 'Welcome back',
    roleCustomer: 'Customer',
    roleAdmin: 'Administrator',
    langToggle: 'العربية (Arabic)',
    
    // Auth Pages
    loginTitle: 'ACCESS SYSTEM Portal',
    loginSubtitle: 'Home maintenance & consultations desk',
    signupTitle: 'CREATE AN ACCOUNT',
    signupSubtitle: 'Quick sign up for booking management',
    fieldEmail: 'Email Address',
    fieldPassword: 'Password',
    fieldName: 'Full Name',
    fieldPhone: 'Phone Number',
    btnSubmitLogin: 'AUTHENTICATE',
    btnSubmitSignup: 'REGISTER ACCOUNT',
    msgNoAccount: "Don't have an account?",
    msgHaveAccount: 'Already registered?',
    linkSignup: 'Create Account',
    linkLogin: 'Go to Log In',
    authError: 'Invalid credentials. Please verify your details.',
    authSuccess: 'Successfully authenticated!',
    signupSuccess: 'Account registered successfully! You can log in now.',

    // Homepage & Categories
    heroTitle: 'DOMESTIC MAINTENANCE',
    heroSubtitle: 'HIGH-CONTRAST BILINGUAL INTERNAL OPERATIONS AND SCHEDULING PLATFORM',
    categoriesHeader: 'SELECT DEPT / SERVICE LINE',
    servicesHeader: 'SERVICES AVAILABLE IN',
    backCategories: '← Back to service categories',
    bookingFeeLabel: 'Booking Fee',
    bookingFeeCurrency: 'SAR',
    consultationNoFee: 'Consultations (Rates customized based on project requirements)',
    clickToBook: 'BOOK SERVICE',
    detailsTitle: 'SERVICE DETAILS',

    // Booking Flow
    bookingFormTitle: 'SCHEDULE SERVICE BOOKING',
    fieldService: 'Selected Service',
    fieldPreferredDate: 'Preferred Date',
    fieldTimeSlot: 'Preferred Time Slot',
    slotMorning: 'Morning slot (8 AM - 12 PM)',
    slotAfternoon: 'Afternoon slot (12 PM - 5 PM)',
    slotEvening: 'Evening slot (5 PM - 9 PM)',
    fieldUrgency: 'Urgency Level',
    urgencyNormal: 'Normal (Standard Schedule)',
    urgencyUrgent: 'Urgent (Within 24 Hours)',
    urgencyEmergency: 'EMERGENCY (Immediate Response Needed)',
    fieldAddress: 'Service Address / Location',
    fieldDescription: 'Fault Details / Request Description',
    fieldPhotos: 'Reference Photos (Up to 3 photos)',
    fileDragDrop: 'Drag & drop photos or click to upload',
    fileLimitMsg: 'JPG/PNG. Maximum 3 files.',
    feeAckLabel: 'I acknowledge and agree to pay the standard booking fee of',
    feeAckLabelConsultation: 'I understand this professional consultation requested is subject to variable expert consulting rates.',
    btnConfirmBooking: 'CONFIRM BOOKING ORDER',
    msgAckRequired: 'You must acknowledge the booking fee terms before submitting.',
    bookingSuccess: 'Booking order placed successfully! Check your dashboard for updates.',

    // Customer Dashboard
    dashboardTitle: 'CUSTOMER DASHBOARD',
    dashboardSubtitle: 'Manage your active service orders and history',
    noBookings: 'No bookings found.',
    btnCancelBooking: 'Cancel Booking',
    btnReschedule: 'Reschedule',
    modalRescheduleTitle: 'Reschedule Booking Date & Time',
    btnSaveReschedule: 'Update Schedule',
    bookingStatus: 'Status',
    bookingDate: 'Date',
    bookingTime: 'Time Slot',
    bookingUrgency: 'Urgency',
    bookingAddress: 'Address',
    bookingDescription: 'Description',
    bookingPhotos: 'Attached Photos',
    statusPending: 'Pending',
    statusConfirmed: 'Confirmed',
    statusInProgress: 'In Progress',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    urgencyNormalLabel: 'Normal',
    urgencyUrgentLabel: 'Urgent',
    urgencyEmergencyLabel: 'Emergency',

    // Admin Dashboard
    adminPortalTitle: 'ADMINISTRATIVE OVERVIEW',
    adminLoginTitle: 'ADMINISTRATIVE DISPATCH PORTAL',
    adminLoginSubtitle: 'Secure terminal for controllers only',
    adminStatsTotal: 'Total Bookings',
    adminStatsPending: 'Pending',
    adminStatsCompleted: 'Completed',
    adminStatsRevenue: 'Total Booking Revenue',
    adminFiltersHeader: 'Filter Bookings',
    filterAll: 'All',
    filterByService: 'By Service',
    filterByStatus: 'By Status',
    filterByUrgency: 'By Urgency',
    filterByDate: 'By Date',
    tblClient: 'Client',
    tblService: 'Service',
    tblDate: 'Date/Slot',
    tblUrgency: 'Urgency',
    tblStatus: 'Status',
    tblActions: 'Actions',
    btnViewDetails: 'Inspect Order',
    adminDetailsTitle: 'INSPECT BOOKING ORDER',
    customerInfo: 'Customer Profile',
    bookingParams: 'Booking Parameters',
    adminActionsHeader: 'Update Booking Level Status',
    tabBookings: 'Dispatch Board',
    tabUsers: 'Client Matrix',
    tabServices: 'Rate Management',
    userColumnName: 'Customer Name',
    userColumnContact: 'Contact Details',
    userColumnBookings: 'Submitted Orders',
    serviceColumnName: 'Service Description',
    serviceColumnCategory: 'Category',
    serviceColumnFee: 'Fixed Booking Fee',
    serviceColumnActions: 'Action',
    btnUpdateFee: 'Adjust Fee',
    modalUpdateFeeTitle: 'Adjust Booking Fee',
    newFeeLabel: 'Enter New Booking Fee (SAR)',
    btnSaveFee: 'Confirm Adjustment',
    confirmStatusSuccess: 'Booking status updated successfully.',
    confirmFeeSuccess: 'Service booking fee successfully revised.',
  },
  ar: {
    appName: 'هوم بلكس',
    appSubtitle: 'الصيانة المحترفة والاستشارات',
    navHome: 'الرئيسية',
    navBookings: 'حجوزاتي',
    navAdmin: 'لوحة التحكم',
    navLogin: 'تسجيل الدخول',
    navSignup: 'إنشاء حساب',
    navLogout: 'تسجيل الخروج',
    welcomeBack: 'مرحباً بك مجدداً',
    roleCustomer: 'عميل',
    roleAdmin: 'مدير النظام',
    langToggle: 'English (الإنجليزية)',

    // Auth Pages
    loginTitle: 'بوابة دخول النظام',
    loginSubtitle: 'مكتب الصيانة المنزلية والاستشارات',
    signupTitle: 'إنشاء حساب جديد',
    signupSubtitle: 'تسجيل سريع لإدارة وتتبع حجوزاتك ومستنداتك',
    fieldEmail: 'البريد الإلكتروني',
    fieldPassword: 'كلمة المرور',
    fieldName: 'الاسم الكامل',
    fieldPhone: 'رقم الهاتف (الجوال)',
    btnSubmitLogin: 'التحقق والمتابعة',
    btnSubmitSignup: 'تسجيل وتفعيل الحساب',
    msgNoAccount: 'ليس لديك حساب؟',
    msgHaveAccount: 'مسجل بالفعل؟',
    linkSignup: 'أنشئ حساباً جديداً',
    linkLogin: 'الانتقال لتسجيل الدخول',
    authError: 'بيانات الاعتماد غير صالحة. يرجى التحقق وإعادة المحاولة.',
    authSuccess: 'تم التحقق والدخول بنجاح!',
    signupSuccess: 'تم إنشاء الحساب بنجاح! يمكنك الآن تسجيل الدخول.',

    // Homepage & Categories
    heroTitle: 'الصيانة المنزلية والمهنية',
    heroSubtitle: 'نظام تشغيل وحجز داخلي عالي التباين ثنائي اللغة',
    categoriesHeader: 'اختر القسم أو خط الخدمة',
    servicesHeader: 'الخدمات المتاحة في قسم',
    backCategories: '← العودة إلى الأقسام الرئيسية',
    bookingFeeLabel: 'رسوم الحجز المسبق',
    bookingFeeCurrency: 'ريال سعودي',
    consultationNoFee: 'استشارات مهنية (تحدد التكلفة بناءً على دراسة متطلبات المشروع)',
    clickToBook: 'حجز الخدمة الآن',
    detailsTitle: 'تفاصيل الخدمة',

    // Booking Flow
    bookingFormTitle: 'جدولة وتأكيد طلب الحجز',
    fieldService: 'الخدمة المختارة',
    fieldPreferredDate: 'التاريخ المفضل لتنفيذ الخدمة',
    fieldTimeSlot: 'فترة الزيارة المفضلة',
    slotMorning: 'الفترة الصباحية (٨ ص - ١٢ م)',
    slotAfternoon: 'فترة بعد الظهر (١٢ م - ٥ م)',
    slotEvening: 'الفترة المسائية (٥ م - ٩ م)',
    fieldUrgency: 'مستوى الأهمية والاستعجال',
    urgencyNormal: 'عادي (مجدول حسب الترتيب الاعتيادي)',
    urgencyUrgent: 'عاجل (خلال ٢٤ ساعة)',
    urgencyEmergency: 'طوارئ قصوى (استجابة فورية للأعطال الحرجة)',
    fieldAddress: 'عنوان أو موقع تقديم الخدمة بالتفصيل',
    fieldDescription: 'وصف الخلل الفني أو متطلبات العمل المطلوب',
    fieldPhotos: 'إرفاق صور توضيحية للمشكلة (٣ صور كحد أقصى)',
    fileDragDrop: 'اسحب الصور وأفلتها هنا أو اضغط للاختيار يدوياً',
    fileLimitMsg: 'JPG/PNG. ٣ ملفات للحد الأقصى.',
    feeAckLabel: 'أقر وأوافق على دفع قيمة رسوم الزيارة والحجز التأسيسية المقدرة بـ',
    feeAckLabelConsultation: 'أدرك تماماً أن هذه الاستشارة الفنية تخضع لأتعاب استشارية متغيرة وفقاً لطبيعة المشروع.',
    btnConfirmBooking: 'تأكيد وإصدار أمر الحجز والاستدعاء',
    msgAckRequired: 'يجب تأكيد الإقرار بالموافقة على رسوم الحجز والخدمة للمتابعة.',
    bookingSuccess: 'تم تسجيل وإرسال طلب الحجز بنجاح! يمكنك متابعته من لوحة التحكم الخاصة بك.',

    // Customer Dashboard
    dashboardTitle: 'لوحة التحكم للعميل',
    dashboardSubtitle: 'إدارة وتتبع أوامر الخدمة الحالية وسجل العمليات السابق',
    noBookings: 'لا توجد طلبات حجز مسجلة حالياً.',
    btnCancelBooking: 'إلغاء الطلب',
    btnReschedule: 'تعديل الموعد',
    modalRescheduleTitle: 'تعديل موعد وفترة زيارة الحجز',
    btnSaveReschedule: 'حفظ الموعد الجديد',
    bookingStatus: 'حالة الطلب',
    bookingDate: 'التاريخ المجدول',
    bookingTime: 'فترة الزيارة',
    bookingUrgency: 'الحالة',
    bookingAddress: 'العنوان',
    bookingDescription: 'تفاصيل العمل',
    bookingPhotos: 'الصور المرفقة',
    statusPending: 'معلق',
    statusConfirmed: 'مؤكد',
    statusInProgress: 'قيد التنفيذ',
    statusCompleted: 'مكتمل',
    statusCancelled: 'ملغي',
    urgencyNormalLabel: 'عادي',
    urgencyUrgentLabel: 'عاجل',
    urgencyEmergencyLabel: 'طوارئ',

    // Admin Dashboard
    adminPortalTitle: 'بوابة التحكم والتشغيل الإدارية',
    adminLoginTitle: 'بوابة دخول الموظفين والإدارة',
    adminLoginSubtitle: 'نظام التحكم الداخلي والمتابعة الآمن للشركة',
    adminStatsTotal: 'إجمالي الطلبات',
    adminStatsPending: 'طلبات معلقة',
    adminStatsCompleted: 'طلبات مكتملة',
    adminStatsRevenue: 'الإيرادات المحققة من رسوم الحجز',
    adminFiltersHeader: 'تصفية وفرز الطلبات',
    filterAll: 'الكل',
    filterByService: 'حسب نوع الخدمة',
    filterByStatus: 'حسب حالة الطلب',
    filterByUrgency: 'حسب الأهمية',
    filterByDate: 'حسب التاريخ',
    tblClient: 'العميل',
    tblService: 'الخدمة المطلوبة',
    tblDate: 'التاريخ / الفترة',
    tblUrgency: 'الأهمية',
    tblStatus: 'الحالة',
    tblActions: 'الإجراءات',
    btnViewDetails: 'معاينة وفحص الطلب',
    adminDetailsTitle: 'تفاصيل ومعاينة أمر الحجز',
    customerInfo: 'بيانات العميل الشخصية',
    bookingParams: 'محددات وجدولة الطلب',
    adminActionsHeader: 'تحديث حالة ومعالجة الطلب',
    tabBookings: 'جدول التشغيل والطلبات',
    tabUsers: 'قاعدة بيانات المشتركين',
    tabServices: 'إدارة وتحديث الأسعار',
    userColumnName: 'اسم العميل',
    userColumnContact: 'معلومات الاتصال والبريد',
    userColumnBookings: 'عدد الطلبات المقدمة',
    serviceColumnName: 'وصف وتفاصيل الخدمة',
    serviceColumnCategory: 'القسم الرئيسي',
    serviceColumnFee: 'رسوم الحجز المحددة حالياً',
    serviceColumnActions: 'إجراء',
    btnUpdateFee: 'تعديل قيمة الرسم',
    modalUpdateFeeTitle: 'تعديل رسم حجز الخدمة',
    newFeeLabel: 'أدخل قيمة رسم الحجز الجديد بالريال السعودي',
    btnSaveFee: 'اعتماد وتحديث السعر',
    confirmStatusSuccess: 'تم تحديث حالة طلب الخدمة بنجاح.',
    confirmFeeSuccess: 'تم تعديل رسوم زيارة الحجز بنجاح وتحديثها في النظام.',
  }
};
